"""
elevator/tiles.py — Tile-based ISA translation framework.

Abstract: "Translations are built by composing code 'tiles' automatically
derived from a high-level description of the source ISA, yielding a nimble
translation framework."

[UNSPECIFIED] The tile grammar, tile derivation mechanism, composition rules,
and the "high-level ISA description" language are entirely unspecified.
The paper PDF was not available. This module provides the abstract interface
that a concrete implementation must satisfy.

The concept of "tiles" in compilation goes back to tree-pattern matching in
code generation (Aho, Ganapathi, Tjiang 1989 — "Code Generation Using Tree
Matching and Dynamic Programming"). Elevator appears to adapt this to
whole-ISA translation rather than expression trees.
"""

from __future__ import annotations

import abc
from dataclasses import dataclass, field
from typing import Callable, Optional


@dataclass
class Tile:
    """
    One translation tile: a source-ISA pattern → target-ISA code template.

    Abstract: tiles are "automatically derived from a high-level description
    of the source ISA."

    [UNSPECIFIED] Whether tiles are:
    - Syntax-directed (match on mnemonic string)
    - Semantics-directed (match on operation type)
    - Automatically generated by a meta-compiler from an ISA spec (likely,
      given "automatically derived")

    Fields
    ------
    name       : human-readable identifier
    matches    : predicate — does this tile apply to a given instruction?
    emit       : function (instr, ctx) → list[str] of AArch64 assembly lines
    cost       : tile selection cost (for optimal tiling, if used)
    """
    name:    str
    matches: Callable[[object], bool]
    emit:    Callable[[object, "TileContext"], list[str]]
    cost:    int = 1

    def applies_to(self, instr: object) -> bool:
        try:
            return self.matches(instr)
        except Exception:
            return False


@dataclass
class TileContext:
    """
    Context passed to tile emit functions.

    [UNSPECIFIED] What information tiles can access during emission.
    Using: source address, register allocation state, and a scratch-register pool.
    """
    source_address: int
    # [UNSPECIFIED] Register mapping between x86-64 and AArch64.
    # Using: a simple fixed mapping (see x86_to_aarch64.py).
    reg_map:        dict[str, str] = field(default_factory=dict)
    scratch_regs:   list[str] = field(default_factory=lambda: ["x9", "x10", "x11"])
    labels:         dict[int, str] = field(default_factory=dict)

    def label_for(self, address: int) -> str:
        if address not in self.labels:
            self.labels[address] = f".L{address:#010x}"
        return self.labels[address]


class TileSelector(abc.ABC):
    """
    Select and apply the best-matching tile for an instruction.

    [UNSPECIFIED] Whether Elevator uses:
    - First-match (leftmost in tile list)
    - Lowest-cost (optimal tiling / dynamic programming)
    - A generated automaton from the ISA description

    Using: first-match for simplicity.
    """

    @abc.abstractmethod
    def select(self, instr: object, ctx: TileContext) -> Optional[Tile]:
        ...

    @abc.abstractmethod
    def emit(self, instr: object, ctx: TileContext) -> list[str]:
        ...


class FirstMatchSelector(TileSelector):
    """
    [UNSPECIFIED] Choice of tiling strategy.
    Using: first-match (ordered tile list, return first applicable tile).
    """

    def __init__(self, tiles: list[Tile]):
        self._tiles = tiles

    def select(self, instr: object, ctx: TileContext) -> Optional[Tile]:
        for tile in self._tiles:
            if tile.applies_to(instr):
                return tile
        return None

    def emit(self, instr: object, ctx: TileContext) -> list[str]:
        tile = self.select(instr, ctx)
        if tile is None:
            mnemonic = getattr(instr, "mnemonic", "?")
            # [UNSPECIFIED] Fallback for untiled instructions.
            # Using: emit a comment placeholder + ud2 (undefined instruction trap).
            return [
                f"// [UNTILED] {mnemonic} {getattr(instr, 'op_str', '')}",
                "// [UNSPECIFIED] No tile defined for this instruction.",
                "// TODO: add tile or handle via emulation stub.",
                "brk #0xdead",   # AArch64 breakpoint — will fault if executed
            ]
        return tile.emit(instr, ctx)
