#!/usr/bin/env bash
# Install or remove the Windows-login -> WSL -> Pleiades container start chain.
# Run from the WSL host with sudo. Use --dry-run before changing a host.
set -euo pipefail

source "${PLEIADES_TERMUX_LIB:-}" 2>/dev/null || true
[[ "${PLEIADES_ENV:-}" == "termux" ]] && {
  echo "[pleiades-autostart] Termux has no WSL/systemd host chain; skipping."
  exit 0
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_TAG="pleiades-autostart"
DRY_RUN=false
UNINSTALL=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --uninstall) UNINSTALL=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 2 ;;
  esac
done

log() { printf '[%s] %s\n' "$LOG_TAG" "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
run() {
  if $DRY_RUN; then
    printf '[DRY-RUN]'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Must run as root (try: sudo bash $0)"

IS_WSL=false
grep -qi microsoft /proc/version 2>/dev/null && IS_WSL=true

# The Windows profile is used only to locate the Windows Startup directory.
# Never infer the WSL Linux account from the Windows profile name.
detect_windows_profile() {
  local raw_profile=""
  if command -v cmd.exe >/dev/null 2>&1 && command -v wslpath >/dev/null 2>&1; then
    raw_profile="$(cmd.exe /C 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r\n')"
    if [[ -n "$raw_profile" && "$raw_profile" != "%USERPROFILE%" ]]; then
      wslpath -u "$raw_profile"
      return 0
    fi
  fi

  local candidate=""
  while IFS= read -r candidate; do
    case "${candidate##*/}" in
      Public|Default|"Default User"|"All Users") continue ;;
    esac
    printf '%s\n' "$candidate"
    return 0
  done < <(find /mnt/c/Users -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | sort)
  return 1
}

WINDOWS_PROFILE=""
VBS_DIR=""
VBS_PATH=""
if $IS_WSL && WINDOWS_PROFILE="$(detect_windows_profile)"; then
  VBS_DIR="$WINDOWS_PROFILE/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup"
  VBS_PATH="$VBS_DIR/Pleiades-WSL-Start.vbs"
fi

SERVICE_FILE="/etc/systemd/system/pleiades-container.service"
BOOT_SCRIPT="/usr/local/bin/pleiades-wsl-boot.sh"
BOOT_SOURCE="$WORKSPACE/root.x86_64/usr/local/bin/pleiades-wsl-boot.sh"
WSL_CONF="/etc/wsl.conf"

uninstall() {
  log "Uninstalling Pleiades host auto-start"
  if systemctl is-enabled pleiades-container.service >/dev/null 2>&1; then
    run systemctl stop pleiades-container.service || true
    run systemctl disable pleiades-container.service || true
  fi
  run rm -f "$SERVICE_FILE"
  run systemctl daemon-reload || true

  if [[ -f "$WSL_CONF" ]] && grep -q 'pleiades-wsl-boot' "$WSL_CONF"; then
    run sed -i '/^command=.*pleiades-wsl-boot/d' "$WSL_CONF"
  fi
  if [[ -n "$VBS_PATH" && -f "$VBS_PATH" ]]; then
    run rm -f "$VBS_PATH"
  fi
  log "Uninstall complete; use 'wsl --shutdown' for a full restart"
}

install_vbs() {
  log "Layer 1: Windows Startup launcher"
  if ! $IS_WSL; then
    log "Not running under WSL; skipping Windows Startup integration"
    return
  fi
  if [[ -z "$VBS_DIR" ]]; then
    log "Windows profile could not be discovered; skipping VBS launcher"
    return
  fi

  local distro="${WSL_DISTRO_NAME:-Ubuntu}"
  if command -v wsl.exe >/dev/null 2>&1; then
    local detected=""
    detected="$(wsl.exe --list --quiet 2>/dev/null | tr -d '\r' | sed '/^[[:space:]]*$/d' | head -n 1)"
    [[ -n "$detected" ]] && distro="$detected"
  fi

  if $DRY_RUN; then
    log "[DRY-RUN] Would write $VBS_PATH for distro $distro"
    return
  fi
  mkdir -p "$VBS_DIR"
  cat > "$VBS_PATH" <<VBS
' Pleiades WSL keepalive launcher. Generated by pleiades-install-host-autostart.sh.
CreateObject("WScript.Shell").Run "wsl -d ${distro} -- bash -lc ""sleep infinity & wait""", 0, False
VBS
  chmod 0644 "$VBS_PATH"
  log "Installed Windows Startup launcher"
}

write_boot_script() {
  if [[ -f "$BOOT_SOURCE" ]]; then
    run install -m 0755 "$BOOT_SOURCE" "$BOOT_SCRIPT"
    return
  fi
  if $DRY_RUN; then
    log "[DRY-RUN] Would write $BOOT_SCRIPT"
    return
  fi
  cat > "$BOOT_SCRIPT" <<'BOOT'
#!/usr/bin/env bash
set -euo pipefail
PLEIADES_ROOT="${PLEIADES_ROOT:-${HOME}/pleiades}"
GENTOO_ROOT="${PLEIADES_ROOT}/rootfs"
[[ -d "$GENTOO_ROOT" ]] || { echo "[pleiades-wsl-boot] rootfs not found"; exit 0; }
pgrep -x systemd-nspawn >/dev/null 2>&1 && { echo "[pleiades-wsl-boot] already running"; exit 0; }
if ! mountpoint -q /run/systemd/nspawn 2>/dev/null; then
  mkdir -p /run/systemd/nspawn
  mount -t tmpfs tmpfs /run/systemd/nspawn
fi
bind_args=()
[[ -d "${PLEIADES_ROOT}/underhall" ]] && bind_args+=(--bind="${PLEIADES_ROOT}/underhall:/mnt/underhall")
exec systemd-nspawn -D "$GENTOO_ROOT" --register=no --keep-unit \
  --resolv-conf=copy-host --hostname=gentoo-codespace "${bind_args[@]}" --boot
BOOT
  chmod 0755 "$BOOT_SCRIPT"
}

install_service() {
  log "Layer 2: WSL systemd service"
  write_boot_script
  if $DRY_RUN; then
    log "[DRY-RUN] Would write and enable $SERVICE_FILE"
    return
  fi
  cat > "$SERVICE_FILE" <<UNIT
[Unit]
Description=Pleiades Gentoo nspawn container
Documentation=https://github.com/Zheke32174/pleiades
After=local-fs.target network.target
Before=shutdown.target
Wants=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${BOOT_SCRIPT}
ExecStop=/usr/local/bin/gentoo-down
TimeoutStartSec=120
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable pleiades-container.service
}

install_wsl_conf() {
  log "Layer 3: wsl.conf fallback"
  if ! $IS_WSL; then
    log "Not running under WSL; skipping wsl.conf"
    return
  fi
  if [[ -f "$WSL_CONF" ]] && grep -q 'pleiades-wsl-boot' "$WSL_CONF"; then
    log "wsl.conf already contains the Pleiades boot command"
    return
  fi
  if $DRY_RUN; then
    log "[DRY-RUN] Would add boot command to $WSL_CONF"
    return
  fi

  if [[ -f "$WSL_CONF" ]] && grep -q '^\[boot\]' "$WSL_CONF"; then
    if ! grep -q '^command=' "$WSL_CONF"; then
      local tmp
      tmp="$(mktemp)"
      sed '/^\[boot\]/a command=/usr/local/bin/pleiades-wsl-boot.sh' "$WSL_CONF" > "$tmp"
      install -m 0644 "$tmp" "$WSL_CONF"
      rm -f "$tmp"
    fi
  else
    cat >> "$WSL_CONF" <<CONF

[boot]
systemd=true
command=/usr/local/bin/pleiades-wsl-boot.sh
CONF
  fi
}

verify() {
  local failed=false
  log "Verification"
  [[ -f "$BOOT_SCRIPT" ]] || { log "Missing boot script: $BOOT_SCRIPT"; failed=true; }
  [[ -f "$SERVICE_FILE" ]] || { log "Missing service: $SERVICE_FILE"; failed=true; }
  if $IS_WSL; then
    [[ -f "$WSL_CONF" ]] || { log "Missing $WSL_CONF"; failed=true; }
    if [[ -n "$VBS_PATH" ]]; then
      [[ -f "$VBS_PATH" ]] || { log "Missing Windows Startup launcher"; failed=true; }
    fi
  fi
  $failed && return 1
  log "All applicable layers are present"
}

log "Environment: $($IS_WSL && printf WSL || printf 'bare metal')"
if $UNINSTALL; then
  uninstall
  exit 0
fi

install_vbs
install_service
install_wsl_conf
$DRY_RUN || verify
log "Done; use 'wsl --shutdown' before testing a fresh Windows login"
